version: "3.7"
services:
  sys-companion-gpt-api:
    container_name: sys-companion-gpt-api
    build:
      context: ./sys-companion-gpt-api
      dockerfile: Dockerfile
    ports:
      - "80:5000"
    env_file:
        - .env

